#===============================================================================#
#                        VETERANIAS - RANGOS DE ASCENSO                         #
#          Plugin que gestiona el genero de los rangos de ascenso               #
#===============================================================================#
# Author: AaronPB - Server: play.minexilon.com                                  #

#===============================================================================#
#  VETERANIAS - GENERAL CONFIGURATION                                           #
#===============================================================================#

# Header of the plugin chat messages
HeaderTag: "&6&l|&3&l|&5&l|&7&l&m| &r&fVeteranias&7&l&m >&r "

# Show debug messages into server console
DebugMode: false

# Enable/disable levitation efect when user promote (duration in seconds)
levitation_effect: true
levitation_duration: 2

# Enable/disable cooldown between two promotions (duration in seconds)
setcooldown: true
cooldowntime: 30

#===============================================================================#
#  VETERANIAS - RANKS CONFIGURATION                                             #
#===============================================================================#

# Prefix and suffix brackets format
titleformatpre: '&7['
titleformatpost: '&7]&r'

# Rank lists
# Each rank MUST have the following format in order to be registered into the
# plugin:
#
# ranktitle: for organization purposes, is not important to define certain name
#   lpgroup: Name of the actual luckperms group
#   lpgroupascend: Name of the next luckperms group. If it is the last one, put 'END'
#   color: Color of the rank, can be & format or HEX format. Ex: '&7' or '#dcdcdc'
#   title_male: Rank title for male users.
#   title_female: Rank title for female users.
#   description: (Optional) Description items that are shown in the ascend inventory
#                You can put a total of 12 items for each rank
#     itemtitle: for organization purposes, is not important to define certain name
#       title: Item display title. Can contain colors with &color. Ex: '&2Hey &elook!'
#       type: Item ID.
#       amount: Item amount, between 1 and 64
#       lore: Lore lines shown on the item. Can contain colors with &color
#       - '&7lore1 &2of the main lore'
#       - '&7lore2 &2of many more lore lines!'
#   cost: 21303 - Cost to promote to this rank.
#   commands: (Optional) Command that will be executed when user promotes.
#             You can put player name variable with the placeholder %player%
#   - 'give %player% diamond_block 1' Example command

ascensionlist:
  Ermitano:
    lpgroup: ermitano
    lpgroupascend: peregrino
    color: '#dcdcdc'
    title_male: 'Ermitaño'
    title_female: 'Ermitaña'
    cost: 10
  Peregrino:
    lpgroup: peregrino
    lpgroupascend: nomada
    color: '&7'
    title_male: 'Peregrino'
    title_female: 'Peregrina'
    cost: 1000
    description:
      item1:
        title: '&6&lIngresa en una ciudad!'
        type: furnace
        amount: 1
        lore:
        - '&7Puedes ingresar en una ciudad,'
        - '&7ya sea invitacion o una ciudad'
        - '&7abierta via &6/t join &ociudad'
      item2:
        title: '&9&lOtro home extra!'
        type: compass
        amount: 1
        lore:
        - '&fHomes totales: 2'
        - '&7Puedes guardar otra localizacion'
        - '&7con &9/sethome &onombre'
    commands: []
  Nomada:
    lpgroup: nomada
    lpgroupascend: explorador
    color: '&7'
    title_male: 'Nomada'
    title_female: 'Nomada'
    description:
      item1:
        title: '&9&lOtro home extra!'
        type: compass
        amount: 1
        lore:
        - '&fHomes totales: 3'
        - '&7Puedes guardar otra localizacion'
        - '&7con &9/sethome &onombre'
    cost: 2500
    commands: []
  Explorador:
    lpgroup: explorador
    lpgroupascend: END
    color: '&7'
    title_male: 'Explorador'
    title_female: 'Exploradora'
    description:
      item1:
        title: '&9&lOtro home extra!'
        type: compass
        amount: 1
        lore:
        - '&fHomes totales: 4'
        - '&7Puedes guardar otra localizacion'
        - '&7con &9/sethome &onombre'
    cost: 4000
    commands: []