author: AaronPB
main: com.aaronpb.veteranias.Veteranias
name: veteranias
description: Plugin de las veteranias del servidor MinExilon
website: www.minexilon.com
version: 0.1.3
api-version: 1.15

depend: [LuckPerms, Vault]

commands:
  ascender:
    aliases:
    - rankup
    usage: /<command>
    description: Command to promote to the next veterania
    permission: veteranias.ascend
    permission-message: No tienes permisos para ejecutar este comando aqui!
#  changeplayergenre:
#    usage: /<command> <player> <male|female>
#    description: Changes player genre
#    permission: veteranias.admin
#    permission-message: No tienes permisos para ejecutar este comando.
  vetreload:
    usage: /<command>
    description: Command for save and rewrite config params
    permission: veteranias.admin
    permission-message: No tienes permisos para ejecutar este comando.

permissions:
  veteranias.ascend:
    description: Needed to use the /rankup command.
    default: op
  veteranias.admin:
    description: Needed to use administrator commands.
    default: op